apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-quick-start
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/prometheus.yaml
  # https://istio.io/latest/docs/ops/integrations/jaeger/#option-1-quick-start
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/jaeger.yaml
  # https://istio.io/latest/docs/setup/getting-started/#dashboard
  # NOTE: kiali uses prometheus.istio-system:9090 by default.
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/kiali.yaml
  - httproute.yaml
