apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://gateway-api.sigs.k8s.io/guides/#install-standard-channel
  # https://github.com/nginx/nginx-gateway-fabric?tab=readme-ov-file#technical-specifications
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
