apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - virtualservice.yaml

  # https://istio.io/latest/docs/ops/integrations/kiali/
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/kiali.yaml
  # http://istio.io/latest/docs/ops/integrations/jaeger/
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/jaeger.yaml
  # https://istio.io/latest/docs/ops/integrations/prometheus/
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/prometheus.yaml
  # https://istio.io/latest/docs/ops/integrations/grafana/
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/grafana.yaml
