apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-sample-app

resources:
  - namespace.yaml
  # https://istio.io/latest/docs/setup/getting-started/#bookinfo
  - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/bookinfo/platform/kube/bookinfo.yaml
  # - https://raw.githubusercontent.com/istio/istio/release-1.28/samples/bookinfo/gateway-api/bookinfo-gateway.yaml
  - httproute.yaml
